### PR TITLE
Fixing object split indexing

### PR DESCRIPTION
**Pull request by kadrlica**
There was a bug in how I was updating the QUICK_OBJECT_ID index for objects that were successfully split. I think this should be corrected now. I've spot-tested on one healpix pixel and things were behaving as expected. I'd appreciate someone with more pandas-fu to take a look the changes [here](https://github.com/kadrlica/desqr/pull/4/files#diff-a827a765a175a8ba98803f918c044a41e300c940f4da13fb50a5b93a9c9e4468R305-R309).

### CODE REVIEW

**Comment by kadrlica** [comment]
@ehneilsen would you be willing to take a look at this?

**Comment by ehneilsen** [comment]
This looks reasonable. The only "gotcha" I see is that lines 308-309 of match.py rely on the DataFrame having unique indexes, which is not guaranteed in general. It happens to be the case here: you never declare an index for the DataFrame you create to pass to split_qcat, so it gets sequential integers by default (and an index name of None), so that is also what split_qcat will return, so that's all okay.
This may go wrong if you ever create a DataFrame with duplicated in the index and pass that to split_qcat, because that's what split_qcat will hand back. This seems unlikely, so the code as you have it should work fine.

**Comment by ehneilsen** [comment]
Also, I suspect switching between recarrays and dataframes would be easier using pandas.DataFrame.to_records and pandas.DataFrame.from_records.

**Comment by kadrlica** [comment]
Thanks Eric. 

The weird creation of the recarray was actually intentional, because I don't think `to_records` allows you to specify the dtype of the columns, and I need to be precise here (it is generally pretty annoying how pandas generalizes data types). At least, that is what I remember from a few years ago.

**Comment by ehneilsen** [comment]
I don't remember when they were added, but to_recarray currently has column_dtypes and index_dtypes options.

**Comment by kadrlica** [comment]
Thanks for the heads up. Documentation says 0.24, but des18a has 0.22.

**Pull request merged**
